---
apiVersion: v1
kind: Service
metadata:
  name: chatbot-svc
  namespace: "{{ .Release.Namespace }}"
  labels:
    app.kubernetes.io/name: {{ include "chatbot.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: {{ .Values.service.ports.http }}
    protocol: TCP
    targetPort: 3000
    {{- if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) (not (empty .Values.service.nodePorts.http)) }}
    nodePort: {{ .Values.service.nodePorts.http }}
    {{- else if eq .Values.service.type "ClusterIP" }}
    nodePort: null
    {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "chatbot.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
